### ISSUE TITLE
Larger interface size (or user's choice)

### ISSUE THREAD

**Issue by HelderRocket** [slaytheboots/Translate#3]
One of the suggestions I would like to give, is that there should be an option in settings, which sets the size of the interface. In my case, I use a 1080p monitor and as you can see in the image, a large part of the screen is wasted.

![image](https://user-images.githubusercontent.com/104467221/211577509-809a55c1-f7f4-4ba8-8bbe-140645082401.png)

**Comment by shef3r** [comment]
sorry for the (rlly) late response. how would you like to go abt this? scaling to make buttons and the font larger or for example making the textboxes and langauge selectors larger while keeping the buttons and fonts the same? i'm not really sure.

**Comment by HelderRocket** [comment]
I would say that both, since in the case of visually impaired people, have the opportunity to adjust the font size to taste, and that this can be changed in settings.

The same with the text boxes, although I don't know if you plan to add anything else to the interface, such as a list of suggested translations, as DeepL does.

(The dictionary thing I imagine is a lot more complex to program, but that depends on whether you feel up to it).

![image](https://user-images.githubusercontent.com/104467221/217532184-f8b1c627-4d4f-4929-94f6-6b59c1e55651.png)

**Comment by shef3r** [comment]
You have been left on a cliffhanger, but I can definitely say that I am working on it now. Actually, I'm almost done. A redesign is on the way in the rewrite branch (if you can't tell, i'm rewriting the whole app, I've learned a lot and the previous code is a mess.) There, you will be able to customize the font size and family. The textboxes will fill the whole screen space. (see attached)

![image](https://github.com/shef3r/Translate/assets/79228174/682a8547-dc15-4a8e-b425-9c7eda1db8fb)

Keep in mind that this font size is not the default. You can change it to be that big in the settings :)

**Comment by shef3r** [comment]
Since this is already resolved and coming in a new version, I will close this issue.
